# Generated by Django 5.0.2 on 2024-04-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_meeting_name_alter_userpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
