# Generated by Django 5.0.2 on 2024-04-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_meeting_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
